// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: rpc/authservice/service.proto

package authservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginRequestV1) Reset() {
	*x = LoginRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_authservice_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestV1) ProtoMessage() {}

func (x *LoginRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_authservice_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestV1.ProtoReflect.Descriptor instead.
func (*LoginRequestV1) Descriptor() ([]byte, []int) {
	return file_rpc_authservice_service_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequestV1) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequestV1) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	ExpiresIn   int64  `protobuf:"varint,2,opt,name=expiresIn,proto3" json:"expiresIn,omitempty"`
}

func (x *LoginResponseV1) Reset() {
	*x = LoginResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_authservice_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponseV1) ProtoMessage() {}

func (x *LoginResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_authservice_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponseV1.ProtoReflect.Descriptor instead.
func (*LoginResponseV1) Descriptor() ([]byte, []int) {
	return file_rpc_authservice_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponseV1) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponseV1) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

var File_rpc_authservice_service_proto protoreflect.FileDescriptor

var file_rpc_authservice_service_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x23, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x62, 0x62, 0x6f, 0x75, 0x64, 0x6c, 0x61, 0x62, 0x2e, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x22, 0x48, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x51,
	0x0a, 0x0f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56,
	0x31, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x49, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x49,
	0x6e, 0x32, 0x83, 0x01, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x56, 0x31, 0x12, 0x72, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x33, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x61, 0x62, 0x62, 0x6f, 0x75, 0x64, 0x6c, 0x61, 0x62, 0x2e, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56,
	0x31, 0x1a, 0x34, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x62, 0x62, 0x6f, 0x75, 0x64, 0x6c, 0x61,
	0x62, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x62, 0x62, 0x6f, 0x75, 0x64, 0x2f, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_authservice_service_proto_rawDescOnce sync.Once
	file_rpc_authservice_service_proto_rawDescData = file_rpc_authservice_service_proto_rawDesc
)

func file_rpc_authservice_service_proto_rawDescGZIP() []byte {
	file_rpc_authservice_service_proto_rawDescOnce.Do(func() {
		file_rpc_authservice_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_authservice_service_proto_rawDescData)
	})
	return file_rpc_authservice_service_proto_rawDescData
}

var file_rpc_authservice_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_authservice_service_proto_goTypes = []interface{}{
	(*LoginRequestV1)(nil),  // 0: com.abboudlab.directoryservice.auth.LoginRequestV1
	(*LoginResponseV1)(nil), // 1: com.abboudlab.directoryservice.auth.LoginResponseV1
}
var file_rpc_authservice_service_proto_depIdxs = []int32{
	0, // 0: com.abboudlab.directoryservice.auth.AuthServiceV1.Login:input_type -> com.abboudlab.directoryservice.auth.LoginRequestV1
	1, // 1: com.abboudlab.directoryservice.auth.AuthServiceV1.Login:output_type -> com.abboudlab.directoryservice.auth.LoginResponseV1
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_authservice_service_proto_init() }
func file_rpc_authservice_service_proto_init() {
	if File_rpc_authservice_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_authservice_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_authservice_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_authservice_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_authservice_service_proto_goTypes,
		DependencyIndexes: file_rpc_authservice_service_proto_depIdxs,
		MessageInfos:      file_rpc_authservice_service_proto_msgTypes,
	}.Build()
	File_rpc_authservice_service_proto = out.File
	file_rpc_authservice_service_proto_rawDesc = nil
	file_rpc_authservice_service_proto_goTypes = nil
	file_rpc_authservice_service_proto_depIdxs = nil
}
