default-tasks:
  resolvers:
    - /home/tabboud/.m2/repository/{{GroupPath}}/{{Product}}/{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  tasks:
    com.palantir.okgo:check-plugin:
      assets:
        - locator:
            id: com.palantir.godel-okgo-asset-golangci-lint:golangci-lint:unspecified
plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.20.0
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.4.0
exclude:
  names:
    - "\\..+"
    - "vendor"
  paths:
    - "godel"
    - "rpc/authservice"
    - "rpc/conjure"
